apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "ws.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ws.selector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
